name: Apply Black formatting to Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install black-nb
        run: |
          python -m pip install --upgrade pip
          pip install black-nb
      - name: Run Black Formatter
        run: |
          black-nb --check .
