name: Clean Jupyter Notebook Metadata

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clean-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ensure Clean Metadata of Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
